spring.application.name=eventoapp

# AQUI FICA A CONEXAO DO BANCO
# spring.mongodb.uri=mongodb+srv://usuario:91019635@cluster0.cgwbnfn.mongodb.net/eventosapp?appName=Cluster0

# CONEXAO RENDER
spring.mongodb.uri=${MONGODB_URI}